# Generated by Django 2.0.4 on 2018-04-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='activity_date',
        ),
    ]
