# Generated by Django 2.0.4 on 2018-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog',
            field=models.CharField(max_length=500),
        ),
    ]
